graph = {
    "Telavi": ["Tbilisi","Lagodekhi"],
    "Lagodekhi": ["Telavi","Tsnori"],
    "Tsnori": ["Lagodekhi", "Sagarejo"],
    "Sagarejo": ["Tsnori","Tbilisi"],
    "Tbilisi": ["Gori","Akhalkalaki","Marneuli","Rustavi","Sagarejo","Telavi","Dusheti"],
    "Dusheti": ["Tbilisi"],
    "Marneuli": ["Tbilisi","Bolnisi"],
    "Rustavi": ["Tbilisi"],
    "Gori": ["Tbilisi","Tskhinvali","Khashuri"],
    "Tskhinvali": ["Gori","Oni"],
    "Khashuri": ["Gori","Kutaisi","Akhaltsikhe"],
    "Akhalkalaki": ["Tbilisi","Akhaltsikhe"],
    "Akhaltsikhe":["Khashuri","Kutaisi","Akhalkalaki"],
    "Bolnisi":["Marneuli"],
    "Oni": ["Tskhinvali","Kutaisi"],
    "Kutaisi": ["Oni","Khashuri","Akhaltsikhe","Tsageri","Zugdidi","Senaki","Ozurgeti"],
    "Tsageri": ["Kutaisi"],
    "Jvari": ["Zugdidi"],
    "Tkvarcheli": ["Sokhumi"],
    "Sokhumi": ["Tkvarcheli","Zugdidi","Gagra"],
    "Gagra": ["Sokhumi"],
    "Zugdidi": ["Jvari","Sokhumi","Kutaisi","Senaki"],
    "Senaki": ["Poti","Ozurgeti","Kutaisi","Zugdidi"],
    "Poti": ["Senaki","Batumi"],
    "Batumi": ["Ozurgeti","Poti"],
    "Ozurgeti": ["Batumi","Senaki","Kutaisi"],
}

heuristic = {
    "Telavi": 9,
    "Lagodekhi": 8,
    "Tsnori": 8,
    "Sagarejo": 7,
    "Tbilisi": 7,
    "Dusheti": 6,
    "Marneuli": 6,
    "Rustavi": 6,
    "Gori": 5,
    "Tskhinvali": 5,
    "Khashuri": 4,
    "Akhalkalaki": 6,
    "Akhaltsikhe": 4,
    "Bolnisi": 6,
    "Oni": 4,
    "Kutaisi": 3,
    "Tsageri": 3,
    "Jvari": 2,
    "Tkvarcheli": 1,
    "Sokhumi": 0,
    "Gagra": 1,
    "Zugdidi": 2,
    "Senaki": 3,
    "Poti": 4,
    "Batumi": 5,
    "Ozurgeti": 4
}

